### ISSUE TITLE
Starting project is throwing Error [ERR_PACKAGE_PATH_NOT_EXPORTED] error

### ISSUE THREAD

**Issue by chenchunaidu** [remix-run/grunge-stack#103]
### Have you experienced this bug with the latest version of the template?

Yeah

### Steps to Reproduce

1. Create a new project with grunge-stack
2. Start application using `npm run dev`

### Expected Behavior

Expected application to run normally.

### Actual Behavior

Following error thrown in cmd and application is not started
```
internal/modules/cjs/loader.js:456
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib' is not defined by "exports" in /Users/chenchunaidu/Programming/Personal/Product/recomnd/node_modules/headers-polyfill/package.json
    at new NodeError (internal/errors.js:322:7)
    at throwExportsNotFound (internal/modules/esm/resolve.js:332:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:565:3)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/Users/chenchunaidu/Programming/Personal/Product/recomnd/node_modules/msw/src/utils/request/MockedRequest.ts:5:25)
    
```

**Comment by machour** [comment]
Can you try updating `msw`to `v0.47.3` and see if that fixes the problem?

If that works, I'll gladly merge a pull request updating the package for this stack :)

**Comment by chenchunaidu** [comment]
yeah @machour this works.
