### ISSUE TITLE
Setup fails

### ISSUE THREAD

**Issue by agonzalezjr** [remix-run/grunge-stack#112]
### Have you experienced this bug with the latest version of the template?

yes

### Steps to Reproduce

```
$ npx create-remix --template remix-run/grunge-stack
? Where would you like to create your app? ./my-remix-app
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes
```
...
```
failed to load config from /Users/agonzalezjr/code/bluejay/my-remix-app/vitest.config.ts

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Error: Cannot find module 'node:path'
Require stack:
- /Users/agonzalezjr/code/bluejay/my-remix-app/node_modules/@vitejs/plugin-react/dist/index.cjs
- /Users/agonzalezjr/code/bluejay/my-remix-app/vitest.config.ts
- /Users/agonzalezjr/code/bluejay/my-remix-app/node_modules/vite/dist/node/chunks/dep-d29b4e33.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/agonzalezjr/code/bluejay/my-remix-app/node_modules/@vitejs/plugin-react/dist/index.cjs:3:14)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object._require.extensions.<computed> [as .js] (file:///Users/agonzalezjr/code/bluejay/my-remix-app/node_modules/vite/dist/node/chunks/dep-d29b4e33.js:64030:17)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/agonzalezjr/code/bluejay/my-remix-app/node_modules/@vitejs/plugin-react/dist/index.cjs',
    '/Users/agonzalezjr/code/bluejay/my-remix-app/vitest.config.ts',
    '/Users/agonzalezjr/code/bluejay/my-remix-app/node_modules/vite/dist/node/chunks/dep-d29b4e33.js'
  ]
}



npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-remix-app-2d72@ test: `vitest "--run"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-remix-app-2d72@ test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/agonzalezjr/.npm/_logs/2022-10-29T19_47_48_046Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-remix-app-2d72@ test:e2e:run: `cross-env PORT=8811 start-server-and-test dev http://localhost:8811 "npx cypress run"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-remix-app-2d72@ test:e2e:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/agonzalezjr/.npm/_logs/2022-10-29T19_47_48_168Z-debug.log
ERROR: "test -- --run" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-remix-app-2d72@ validate: `run-p "test -- --run" lint typecheck test:e2e:run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-remix-app-2d72@ validate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/agonzalezjr/.npm/_logs/2022-10-29T19_47_48_215Z-debug.log
🚨 Oops, remix.init failed

Command failed: npm run validate 
```

### Expected Behavior

Setup finishes without errors.

### Actual Behavior

Setup fails.

**Comment by mcansh** [comment]
what version of node are you using?
