### ISSUE TITLE
@prisma/client did not initialize yet

### ISSUE THREAD

**Issue by zhex900** [remix-run/grunge-stack#163]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

run `arc deploy --staging --prune`

### Expected Behavior

I am expecting this to work

### Actual Behavior

After deploying the app to AWS. 
The lambda gives this error: 

```
"errorType": "Error",
    "errorMessage": "@prisma/client did not initialize yet. Please run \"prisma generate\" and try to import it again.\nIn case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues",
    "stack": [
        "Error: @prisma/client did not initialize yet. Please run \"prisma generate\" and try to import it again.",
        "In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues",
        "    at new PrismaClient (/var/task/node_modules/.prisma/client/index.js:43:11)",
        "    at Object.<anonymous> (/var/app/database/db.server.ts:21:21)",
        "    at Module._compile (node:internal/modules/cjs/loader:1198:14)",
        "    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)",
        "    at Module.load (node:internal/modules/cjs/loader:1076:32)",
        "    at Function.Module._load (node:internal/modules/cjs/loader:911:12)",
        "    at Module.require (node:internal/modules/cjs/loader:1100:19)",
        "    at require (node:internal/modules/cjs/helpers:108:18)",
        "    at _tryRequireFile (file:///var/runtime/index.mjs:976:37)",
        "    at _tryRequire (file:///var/runtime/index.mjs:1026:25)"
    ]
```

`server/node_modules/.prisma/client/index.js` Looks like this file is not updated.

**Comment by MichaelDeBoey** [comment]
@zhex900 I'm going to close this ticket as this stack doesn't use Prisma
