### ISSUE TITLE
✘ [ERROR] Could not resolve "@aws-sdk/client-dynamodb"

### ISSUE THREAD

**Issue by valbaca** [remix-run/grunge-stack#193]
### Have you experienced this bug with the latest version of the template?

yes

### Steps to Reproduce

Ran  the following with `alias pn=pnpm`
```
valbaca@maxbook js % pn dlx create-remix@latest --template remix-run/grunge-stack

 remix   v2.12.1 💿 Let's build a better website...

   dir   Where should we create your new project?
         ./hello-grunge

      ◼  Template: Using remix-run/grunge-stack...
      ✔  Template copied

   git   Initialize a new git repository?
         Yes

  deps   Install dependencies with pnpm?
         Yes

  init   This template has a remix.init script. Do you want to run it?
         Yes

      ✔  Dependencies installed

      ✔  Git initialized
      ✔  Dependencies for remix.init script installed

      ◼  Running template's remix.init script...

? Do you want to run the build/tests/etc to verify things are setup properly? Yes

```

### Expected Behavior

Successful startup after initial setup

### Actual Behavior

```
valbaca@maxbook hello-grunge % pn dev

> hello-grunge-b2cc@ dev /Users/valbaca/Code/js/hello-grunge
> remix dev --manual -c "arc sandbox -e testing"


 💿  remix dev

⚠️  Test routes enabled.
 info  building...
✘ [ERROR] Build failed with 4 errors:
node_modules/.pnpm/@architect+functions@8.1.6/node_modules/@architect/functions/src/tables/legacy.js:16:25: ERROR: Could not resolve "@aws-sdk/client-dynamodb"
node_modules/.pnpm/@architect+functions@8.1.6/node_modules/@architect/functions/src/tables/legacy.js:18:28: ERROR: Could not resolve "@aws-sdk/lib-dynamodb"
node_modules/.pnpm/@architect+functions@8.1.6/node_modules/@architect/functions/src/tables/legacy.js:24:25: ERROR: Could not resolve "aws-sdk/clients/dynamodb"
node_modules/.pnpm/@architect+functions@8.1.6/node_modules/@architect/functions/src/tables/legacy.js:57:40: ERROR: Could not resolve "@smithy/node-http-handler" [plugin css-bundle-plugin]

    app/root.tsx:20:30:
      20 │ import { cssBundleHref } from "@remix-run/css-bundle";
         ╵                               ~~~~~~~~~~~~~~~~~~~~~~~

  This error came from the "onLoad" callback registered here:

    node_modules/.pnpm/@remix-run+dev@2.12.1_@remix-run+react@2.12.1_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_roc5sjsp5ppwfghrzndgv6kr4u/node_modules/@remix-run/dev/dist/compiler/plugins/cssBundlePlugin.js:35:12:
      35 │       build.onLoad({
         ╵             ~~~~~~

    at setup (/Users/valbaca/Code/js/hello-grunge/node_modules/.pnpm/@remix-run+dev@2.12.1_@remix-run+react@2.12.1_react-dom@18.3.1_react@18.3.1__react@18.3.1_typ_roc5sjsp5ppwfghrzndgv6kr4u/node_modules/@remix-run/dev/dist/compiler/plugins/cssBundlePlugin.js:35:13)
    at handlePlugins (/Users/valbaca/Code/js/hello-grunge/node_modules/.pnpm/esbuild@0.17.6/node_modules/esbuild/lib/main.js:1279:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)


✘ [ERROR] Could not resolve "@aws-sdk/client-dynamodb"

    node_modules/.pnpm/@architect+functions@8.1.6/node_modules/@architect/functions/src/tables/legacy.js:16:25:
      16 │     let dynamo = require('@aws-sdk/client-dynamodb')
         ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@aws-sdk/client-dynamodb" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.


✘ [ERROR] Could not resolve "@aws-sdk/lib-dynamodb"

    node_modules/.pnpm/@architect+functions@8.1.6/node_modules/@architect/functions/src/tables/legacy.js:18:28:
      18 │     let docclient = require('@aws-sdk/lib-dynamodb')
         ╵                             ~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@aws-sdk/lib-dynamodb" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.


✘ [ERROR] Could not resolve "aws-sdk/clients/dynamodb"

    node_modules/.pnpm/@architect+functions@8.1.6/node_modules/@architect/functions/src/tables/legacy.js:24:25:
      24 │     let dynamo = require('aws-sdk/clients/dynamodb')
         ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "aws-sdk/clients/dynamodb" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.


✘ [ERROR] Could not resolve "@smithy/node-http-handler"

    node_modules/.pnpm/@architect+functions@8.1.6/node_modules/@architect/functions/src/tables/legacy.js:57:40:
      57 │       let { NodeHttpHandler } = require('@smithy/node-http-handler')
         ╵                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@smithy/node-http-handler" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.
```

**Comment by valbaca** [comment]
I'm new to Remix Stacks, so not sure if this is known or not, figured I'd Open an Issue first.

I'm guessing it's an outdated `architect` and/or incompatibility  with dynamodb

**Comment by valbaca** [comment]
Same issue when running with npx.

macOS, node v22.9.0

**Comment by quantuminformation** [comment]
del node mods, and lock file, re install ?

**Comment by elliotfleming** [comment]
I have this exact issue on a new project (using npx). Not sure where to go from here...

Is this still an active project? Are others NOT getting these errors on new installs? This repo is referenced as an official stack on the [remix website](https://remix.run/docs/en/main/guides/templates#official-stacks) so I presumed it would just work out of the box but I never got past the first command: `npx create-remix@latest --template remix-run/grunge-stack`. The same things happens if you run `npm run dev`.

Removing `/node-modules` and `/package-lock.json` and reinstalling `npm install` does not solve the issue.

I'm using node v22.8.0

**Comment by quantuminformation** [comment]
The repo hasn't been updated in a while, there is an open vite pr too that has been sitting around for months. I would prob start with SST instead

**Comment by nacho008** [comment]
I read the migration from architecture 10 to 11 and included a couple of new devDependencies needed

`    "@aws-sdk/client-apigatewaymanagementapi": "^3.713.0",
    "@aws-sdk/client-dynamodb": "^3.713.0",
    "@aws-sdk/client-s3": "^3.713.0",
    "@aws-sdk/client-sns": "^3.713.0",
    "@aws-sdk/client-sqs": "^3.713.0",
    "@aws-sdk/client-ssm": "^3.713.0",
    "@aws-sdk/lib-dynamodb": "^3.713.0",`

and the browserPolyfill config in the remix.config file

`browserNodeBuiltinsPolyfill: { modules: { querystring: true } },`

As of now, i run `npm run dev` after following previous instructions from readme file, and it worked.
Hope it helps
