### ISSUE TITLE
cypress smoke tests fail out of the box

### ISSUE THREAD

**Issue by sfatzinger** [remix-run/grunge-stack#85]
### Have you experienced this bug with the latest version of the template?

yes

### Steps to Reproduce

- I created a new project using the `grunge-stack` template by running `npx create-remix --template remix-run/grunge-stack`
- I ran `npx run validate`
- The smoke tests fail both locally and in github actions

```
====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        10.3.0                                                                         │
  │ Browser:        Electron 100 (headless)                                                        │
  │ Node Version:   v14.19.3 (/<redacted>/.nvm/versions/node/v14.19.3/bin/node)              │
  │ Specs:          1 found (smoke.cy.ts)                                                          │
  │ Searched:       cypress/e2e/**/*.cy.{js,jsx,ts,tsx}                                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  smoke.cy.ts                                                                     (1 of 1)


  smoke tests
    1) should allow you to register and login
    2) should allow you to make a note


  0 passing (3s)
  2 failing

  1) smoke tests
       should allow you to register and login:
     Error: The following error originated from your application code, not from Cypress.

  > Hydration failed because the initial UI does not match what was rendered on the server.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application
      at throwOnHydrationMismatch (http://localhost:8811/_static/build/entry.client-TUK4SINB.js:8993:17)
      at tryToClaimNextHydratableInstance (http://localhost:8811/_static/build/entry.client-TUK4SINB.js:9014:15)
      at updateHostComponent (http://localhost:8811/_static/build/entry.client-TUK4SINB.js:14184:13)
      at beginWork (http://localhost:8811/_static/build/entry.client-TUK4SINB.js:15256:22)
      at HTMLUnknownElement.callCallback2 (http://localhost:8811/_static/build/entry.client-TUK4SINB.js:3458:22)
      at Object.invokeGuardedCallbackDev (http://localhost:8811/_static/build/entry.client-TUK4SINB.js:3483:24)
      at invokeGuardedCallback (http://localhost:8811/_static/build/entry.client-TUK4SINB.js:3517:39)
      at beginWork$1 (http://localhost:8811/_static/build/entry.client-TUK4SINB.js:19039:15)
      at performUnitOfWork (http://localhost:8811/_static/build/entry.client-TUK4SINB.js:18475:20)
      at workLoopSync (http://localhost:8811/_static/build/entry.client-TUK4SINB.js:18411:13)

  2) smoke tests
       should allow you to make a note:
     Error: The following error originated from your application code, not from Cypress.

  > Hydration failed because the initial UI does not match what was rendered on the server.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application
      at throwOnHydrationMismatch (http://localhost:8811/_static/build/entry.client-TUK4SINB.js:8993:17)
      at tryToClaimNextHydratableInstance (http://localhost:8811/_static/build/entry.client-TUK4SINB.js:9014:15)
      at updateHostComponent (http://localhost:8811/_static/build/entry.client-TUK4SINB.js:14184:13)
      at beginWork (http://localhost:8811/_static/build/entry.client-TUK4SINB.js:15256:22)
      at HTMLUnknownElement.callCallback2 (http://localhost:8811/_static/build/entry.client-TUK4SINB.js:3458:22)
      at Object.invokeGuardedCallbackDev (http://localhost:8811/_static/build/entry.client-TUK4SINB.js:3483:24)
      at invokeGuardedCallback (http://localhost:8811/_static/build/entry.client-TUK4SINB.js:3517:39)
      at beginWork$1 (http://localhost:8811/_static/build/entry.client-TUK4SINB.js:19039:15)
      at performUnitOfWork (http://localhost:8811/_static/build/entry.client-TUK4SINB.js:18475:20)
      at workLoopSync (http://localhost:8811/_static/build/entry.client-TUK4SINB.js:18411:13)
```

### Expected Behavior

The cypress smoke tests should pass out of the box on a newly created project using the grunge-stack template

### Actual Behavior

The cypress smoke tests fail out of the box

**Comment by sfatzinger** [comment]
I just created a new project using the grunge-stack template, and get this error now running the validation script:
```
server.ts:9:3 - error TS2739: Type 'typeof import("/Users/sfatzinger/dev/projects/grunge-sandbox/node_modules/@remix-run/dev/server-build")' is missing the following properties from type 'ServerBuild': publicPath, assetsBuildDirectory

9   build,
    ~~~~~

  node_modules/@remix-run/architect/dist/server.d.ts:18:5
    18     build: ServerBuild;
           ~~~~~
    The expected type comes from property 'build' which is declared here on type '{ build: ServerBuild; getLoadContext?: GetLoadContextFunction | undefined; mode?: string | undefined; }'


Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grunge-sandbox-d73e@ typecheck: `tsc -b && tsc -b cypress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grunge-sandbox-d73e@ typecheck script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sfatzinger/.npm/_logs/2022-07-15T15_26_41_621Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grunge-sandbox-d73e@ test:e2e:run: `cross-env PORT=8811 start-server-and-test dev http://localhost:8811 "npx cypress run"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grunge-sandbox-d73e@ test:e2e:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sfatzinger/.npm/_logs/2022-07-15T15_26_41_762Z-debug.log
ERROR: "typecheck" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grunge-sandbox-d73e@ validate: `run-p "test -- --run" lint typecheck test:e2e:run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grunge-sandbox-d73e@ validate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sfatzinger/.npm/_logs/2022-07-15T15_26_41_813Z-debug.log
🚨 Oops, remix.init failed

Command failed: npm run validate
```

**Comment by sfatzinger** [comment]
Thanks! After updating to the nightly build you pointed me at, `tsc` works correctly, but I'm getting this error in the build now:
```
✓ Sandbox Started file watcher
Watching Remix app in development mode...
⚠️  Test routes enabled.
Done in 202ms.

✘ [ERROR] Could not resolve ".//<path>/cypress/support/test-routes/create-user.ts"

    browser-route-module:/<path>/cypress/support/test-routes/create-user.ts?browser:1:24:
      1 │ ...ult } from ".//<path>/...
        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Build failed with 1 error:
browser-route-module:/<path>/cypress/support/test-routes/create-user.ts?browser:1:24: ERROR: Could not resolve ".//<path>/cypress/support/test-routes/create-user.ts"
💿 Built in 447ms
```

I cleaned the build (by deleting that dir, don't see a script for that), and installed packages, but no luck.

**Comment by mcansh** [comment]
i’ve noticed that too, i’ll see if i can figure out what’s going on with that in a bit

**Comment by lukasalvarezdev** [comment]
This error happens whenever I try to update any remix project to React 18. For example, this happens too with the indie-stack, so maybe it is an error with Remix?
