### ISSUE TITLE
Deploy Error

### ISSUE THREAD

**Issue by robsonkades** [remix-run/grunge-stack#93]
### Have you experienced this bug with the latest version of the template?

yes

### Steps to Reproduce

Deploy new application on aws  with github actions.

### Expected Behavior

Deploy with Success

### Actual Behavior

```
Run arc deploy --production --prune
  arc deploy --production --prune
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    npm_config_cache: /home/runner/.npm
    CI: true
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
         App ⌁ remix-aws-451b
      Region ⌁ us-west-[2](https://github.com/robsonkades/remix-run-aws/runs/7683794292?check_suite_focus=true#step:10:2)
     Profile ⌁ Set via environment
     Version ⌁ Architect 10.4.0
         cwd ⌁ /home/runner/work/remix-run-aws/remix-run-aws

⚬ Hydrate Finding dependencies
⚬ Hydrate Hydrating dependencies in 1 path
⚬ Hydrate Hydrating server/
✓ Hydrate Hydrated server/
  | npm i --production: added 97 packages from 165 contributors and audited 98 packages in [3](https://github.com/robsonkades/remix-run-aws/runs/7683794292?check_suite_focus=true#step:10:3).92[4](https://github.com/robsonkades/remix-run-aws/runs/7683794292?check_suite_focus=true#step:10:4)s
  | npm i --production: 41 packages are looking for funding
  | npm i --production: run `npm fund` for details
  | npm i --production: found 0 vulnerabilities
  | npm i --production: npm notice created a lockfile as package-lock.json. You should commit this file.
✓ Hydrate Successfully hydrated dependencies
⚬ Deploy This Lambda should ideally be under [5](https://github.com/robsonkades/remix-run-aws/runs/7683794292?check_suite_focus=true#step:10:5)MB for optimal performance:
  | server (29,535KB)
⚬ Deploy Creating new private deployment bucket: ****
⚬ Deploy Initializing deployment
  | Stack ... RemixAws451bProduction
  | Bucket .. ****
⚬ Deploy Created deployment templates
⚬ Deploy Generating CloudFormation deployment...
✓ Deploy Generated CloudFormation deployment
⚬ Deploy Deploying & building infrastructure...
deploy failed! 
Uploading to 8eb4[6](https://github.com/robsonkades/remix-run-aws/runs/7683794292?check_suite_focus=true#step:10:6)d[7](https://github.com/robsonkades/remix-run-aws/runs/7683794292?check_suite_focus=true#step:10:7)e0bc6041699a44022[8](https://github.com/robsonkades/remix-run-aws/runs/7683794292?check_suite_focus=true#step:10:8)4d7df[9](https://github.com/robsonkades/remix-run-aws/runs/7683794292?check_suite_focus=true#step:10:10)d.template  8892 / 8892.0  ([10](https://github.com/robsonkades/remix-run-aws/runs/7683794292?check_suite_focus=true#step:10:11)0.00%)
Waiting for changeset to be created..
Waiting for stack create/update to complete

Failed to create/update the stack. Run the following command
to fetch the list of events leading up to the failure
aws cloudformation describe-stack-events --stack-name RemixAws451bProduction

Error: 
Uploading to 8eb46d7e0bc6041699a4402284d7df9d.template  8892 / 8892.0  (100.00%)
Waiting for changeset to be created..
Waiting for stack create/update to complete

Failed to create/update the stack. Run the following command
to fetch the list of events leading up to the failure
aws cloudformation describe-stack-events --stack-name RemixAws451bProduction

    at ChildProcess.<anonymous> (/opt/hostedtoolcache/node/14.20.0/x64/lib/node_modules/@architect/architect/node_modules/@architect/deploy/src/sam/utils/spawn.js:23:16)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:475:[12](https://github.com/robsonkades/remix-run-aws/runs/7683794292?check_suite_focus=true#step:10:13))
    at maybeClose (internal/child_process.js:1088:[16](https://github.com/robsonkades/remix-run-aws/runs/7683794292?check_suite_focus=true#step:10:17))
    at Process.ChildProcess._handle.onexit (internal/child_process.js:[29](https://github.com/robsonkades/remix-run-aws/runs/7683794292?check_suite_focus=true#step:10:30)6:5)
Error: Process completed with exit code 1.
```

**Comment by BradLeftley** [comment]
Think I had this issue before which version of Node are you running?
